# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9360ff2203a2806c0d14aded6a3a5d4edecb976fd966b5dd4d9660617c9cd0b09445e33d83b07b7e9d81310aa1edc02816eb6c6e6216d67c13ca28c8aebad5a4

test:
  secret_key_base: f48e8f51fe93b066df927a068f510f3cecee03f36bd471af43d66f026131a5fcb6827766d80f545448f04faa44a0eb24c7e3ace96934bf1c8821cb3cf7c81c05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
